-- WTF.
print("============ Random Mail Subject Generator - Help ============")
print("The random mail subject generator will return 3 suspicious strings\nby default unless you append arguments and parameters")
print() -- I could have used \n, but this is way easier to read.
print("USAGE")
print("","lua rmsg.lua [-arguments] [parameters]")
print()
print("ARGUMENTS and PARAMETERS")
print("","-h    --help                display help (that's what you see right now)")
print("","-w    --words [number]      define the number of words generated")
print("","-c    --category [String]   define the category of suspicious string.")
print("","-s    --show 				  show available categories.")
print("","-r    --random              same as evaluating program without parameters")
print("","      --about               who made this piece of unnecessary software?")
print("","-d    --debug 			  debugging mode.")
print()
