# This list is taken from http://rt.com/usa/dhs-list-suspicious-words-302/ and parsed via ocr.
strings = [
        "domestic_security":
            string: [
                "assassination",
                "emergency",
                "management",
                "gangs",
                "attack",
                "response",
                "national security",
                "domestic security",
                "first responder",
                "state of emergency",
                "drill",
                "homeland security",
                "security",
                "Exercise",
                "maritime",
                "domain awareness",
                "breach",
                "cops",
                "MDA",
                "threat",
                "law enforcement",
                "national preparedness",
                "authorities",
                "initiative",
                "SWAT",
                "disaster assistance",
                "Militia",
                "screening",
                "Cops MDA threat",
                "Shooting",
                "Lockdown",
                "DNDO",
                "domestic nuclear shots refired bomb",
                "evacuation crash",
                "hostage",
                "riot",
                "emergency landing",
                "pipe bomb",
                "dirt bomb team",
                "DMAT facility",
                "domestic nuclear detection",
                "organized crime"
            ],
        "hazmat_and_nuclear":
            string: [
                "nuclear",
                "Biological infection",
                "Spillover",
                "chemical spill event",
                "anthrax",
                "suspicious package",
                "suspicious device",
                "chemical blister agent",
                "national laboratory",
                "biological exposure",
                "nuclear facility",
                "epedemic burn",
                "nuclear threat",
                "hazardous nerve agent",
                "hazardous material",
                "incident",
                "Ricin",
                "industrial spill",
                "Sarin",
                "radiation",
                "infection",
                "North Korea",
                "DPRK",
                "radioactive powder"
            ],
        "health_concern":
            string: [
                "outbreak",
                "salmonella agriculture",
                "contamination",
                "small pox listeria",
                "exposure",
                "plague",
                "symptoms",
                "virus",
                "human to human",
                "mutation",
                "evacuation",
                "human to animal",
                "resistant",
                "bacteria",
                "influenza",
                "antiviral",
                "recall center for disease control",
                "wave",
                "ebola",
                "CDC",
                "Pandemic",
                "H1N1",
                "Tuberculosis",
                "TB",
                "Pork",
                "avian agro",
                "terror swine",
                "H5N1",
                "FMD",
                "public health",
                "food poisoning",
                "drug administration",
                "FDA",
                "DEA",
                "infection",
                "Tamiﬂu",
                "world health organizations",
                "quarantine",
                "noro virus",
                "WHO",
                "epedemic viral",
                "hemorrhagic fever",
                "E. Coli"
            ],
        "infrastructure_security":
            string: [
                "infrastructure security",
                "airplane",
                "airport",
                "chemical fire",
                "critical infrastructure",
                "subway electric",
                "BART failure and outage",
                "AMTRAK",
                "MARTA",
                "black out",
                "collapse",
                "port authority",
                "computer infrastructure",
                "Biosurveillance",
                "Integration Dock",
                "Bridge",
                "telecommunications",
                "transportation security",
                "grid delays",
                "national infrastructure",
                "power service disruption",
                "smart power lines",
                "WMATA",
                "body scanner",
                "southwest border violence",
                "drug canel",
                "fort Hancock",
                "gunfight",
                "violence",
                "San Diego",
                "gang",
                "Ciudad Juarez",
                "kidnap",
                "drug nogales",
                "calderon",
                "narcotics",
                "Sonora Reyosa",
                "Cocaine",
                "columbia bust",
                "marijuana",
                "Tamaulipas",
                "Heroin",
                "MS I3",
                "MS-I 3",
                "Meth Lab",
                "Border drug control",
                "drug war",
                "drug trade",
                "ice mud slide",
                "mud slide",
                "hurricane",
                "erosion",
                "mexico",
                "mexican army",
                "illegal immigrants",
                "Cartel",
                "Methamphetamine",
                "smuggling",
                "smugglers",
                "southwest cartel",
                "Michoacana",
                "Sinaloa",
                "La Familia Guzman",
                "Tijuana Reynosa",
                "Arellano-Felix",
                "Torrreon Nuevo",
                "Leon Beltran-Leyva",
                "Tucson Narco banners",
                "Mexicles",
                "Consular Shootout",
                "El Paso Execution"
            ],
        "terrorism":
            string: [
                "terrorism",
                "IED",
                "improvised explosive suspicious substance",
                "Al Qaeda",
                "AQAP",
                "arabian wedding",
                "terror",
                "attack",
                "Hamas",
                "Iraq",
                "FARC",
                "afghanistand forces",
                "TTP",
                "Tehrik-i-Taliban",
                "Iran",
                "IRA",
                "Irish Republican Army",
                "Pakistan",
                "Pakistan ETA",
                "Euskadi ta Askatasuna",
                "Yemen",
                "holidays",
                "Pirates",
                "Basque Seperatists",
                "Environmental terrorist",
                "Hezbollah",
                "Extremism",
                "Tamil Tigers Somalia",
                "conventional weapon",
                "PLF",
                "Palestine Liberation Nigeria",
                "Radicals",
                "dirty bomb",
                "organization",
                "homegrown",
                "enriched",
                "car bomb",
                "nuclear",
                "jihad",
                "nationalist",
                "jihadist",
                "chemical weapon",
                "Taliban",
                "Recmitment",
                "biological weapon",
                "weapons cache",
                "fundamentalism",
                "ammonium nitrate",
                "suicide bomber",
                "islamist",
                "suicide attack"
            ],
        "cyber_security":
            string: [
                "cyber security",
                "hacker",
                "botnet",
                "spammer",
                "china",
                "DDoS",
                "dedicated denial of service",
                "phishing",
                "conficker",
                "rootkit",
                "worm",
                "denial of service",
                "network scanners",
                "malware",
                "cain and abel",
                "social media",
                "virus",
                "brute force",
                "brute forcing",
                "trojan",
                "MySQL Injection",
                "keylogger",
                "cyber attack",
                "cyber terror"
            ],

]

# This list is taken from http://rt.com/usa/dhs-list-suspicious-words-302/ and parsed via ocr.
